version: '3.5'
services:


    
    database:
        
        build:
            context: .
            dockerfile: db.Dockerfile
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: api
            MYSQL_DATABASE: apidb
            MYSQL_USER: apiuser
            MYSQL_PASSWORD: apipass

        command: --default-authentication-plugin=mysql_native_password
        
        volumes:
            - db-volume:/var/lib/mysql
    
    
    golang:
        build: 
            context: .
            dockerfile: go.Dockerfile
        ports:
            - "5000:5000"
        depends_on: 
            - database

volumes:
    db-volume:
    golang: